package com.example.grader.service;

import org.junit.jupiter.api.Test;

import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Danh sách package đề cho phép chỉ THU HẸP được, không cài thêm được gì: thư viện phải có sẵn
 * trong ảnh chấm. Bộ kiểm này soi phần bóc tên package từ pubspec.lock của ảnh, thứ quyết định
 * bộ đề nào bị chặn lúc lưu.
 */
class GoiChoPhepTest {

    /** Mẫu rút gọn từ /app/pubspec.lock của ảnh grading-base thật. */
    private static final String LOCK = """
            # Generated by pub
            packages:
              flutter:
                dependency: "direct main"
                description: flutter
                source: sdk
                version: "0.0.0"
              sqflite:
                dependency: "direct main"
                description:
                  name: sqflite
                  sha256: "abc"
                  url: "https://pub.dev"
                source: hosted
                version: "2.4.2+1"
              sqflite_common:
                dependency: transitive
                description:
                  name: sqflite_common
                source: hosted
                version: "2.5.5"
              intl:
                dependency: "direct main"
                description:
                  name: intl
                source: hosted
                version: "0.20.2"
            sdks:
              dart: ">=3.10.0 <4.0.0"
              flutter: ">=3.27.0"
            """;

    @Test
    void bocDuocCaGoiKhaiTrucTiepLanGoiKeoTheo() {
        Set<String> ten = ExamService.goiTuLock(LOCK);

        assertTrue(ten.contains("sqflite"), "gói khai trực tiếp phải có");
        // sqflite_common không khai trong pubspec nhưng vẫn import được vì nằm trong package
        // graph đã resolve. Bóc thiếu nó là chặn oan đúng tên bộ đề FA26 đang cho phép.
        assertTrue(ten.contains("sqflite_common"), "gói kéo theo cũng import được nên phải có");
        assertTrue(ten.contains("intl"));
        assertTrue(ten.contains("flutter") && ten.contains("flutter_test"), "hai gói lõi luôn có");
    }

    @Test
    void khongNhamKhoiSdksThanhTenGoi() {
        Set<String> ten = ExamService.goiTuLock(LOCK);

        // "dart" và "flutter" nằm trong khối sdks ở cuối file, thụt đúng 2 dấu cách y hệt tên
        // package. Bám theo khối đang đứng chứ không theo độ thụt thì mới không nhặt nhầm.
        assertFalse(ten.contains("dart"), "dart là SDK, không phải package import được");
        assertEquals(Set.of("flutter", "flutter_test", "sqflite", "sqflite_common", "intl"), ten);
    }

    @Test
    void khongDocDuocThiCoiNhuKhongBiet() {
        // Docker tắt, chưa build ảnh, hoặc file hỏng: phải trả rỗng để phần gọi BỎ QUA phép
        // kiểm. Trả về {flutter, flutter_test} là biến "không biết" thành "ảnh chỉ có hai gói"
        // rồi chặn sạch mọi bộ đề.
        assertTrue(ExamService.goiTuLock(null).isEmpty());
        assertTrue(ExamService.goiTuLock("").isEmpty());
        assertTrue(ExamService.goiTuLock("packages:\n").isEmpty());
        assertTrue(ExamService.goiTuLock("khong-phai-lock").isEmpty());
    }
}
