package com.example.grader.service;

import com.example.grader.entity.GradingRuntimeSetting;
import com.example.grader.repository.GradingRuntimeSettingRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.lang.reflect.Field;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Module GradingLibrary — các sheet UT26…UT31.
 *
 * <p>Hai nhóm việc khác hẳn nhau nhưng cùng một màn hình: đọc/ghi danh sách thư viện của ảnh
 * chấm, và chỉnh hiệu năng chấm. Chỗ dễ sai nhất ở nhóm đầu là phân biệt "ảnh KHÔNG có gói này"
 * với "CHƯA ĐỌC ĐƯỢC ảnh" — nhầm hai cái đó là chặn oan cả bộ đề; ở nhóm sau là biên của các
 * khoảng hợp lệ, vì hàm cố ý KHÔNG cắt gọt giá trị người dùng gõ.
 */
class GradingLibraryUnitTest {

    @TempDir Path thuMuc;

    /** Đặt thẳng field @Value — các service này nhận cấu hình bằng field injection. */
    private static void datField(Object doiTuong, String ten, Object giaTri) throws Exception {
        Field f = doiTuong.getClass().getDeclaredField(ten);
        f.setAccessible(true);
        f.set(doiTuong, giaTri);
    }

    // ══════════════════ UT26 — ExamService.goiTuLock ══════════════════

    private static final String LOCK_DAY_DU = """
            # Generated by pub
            packages:
              intl:
                dependency: "direct main"
                version: "0.19.0"
              sqflite:
                dependency: "direct main"
                version: "2.3.0"
            sdks:
              dart: ">=3.0.0 <4.0.0"
              flutter: ">=3.24.0"
            """;

    static Stream<Arguments> ut26_khongBocDuoc() {
        return Stream.of(
                Arguments.of("UTCID01", (String) null),
                Arguments.of("UTCID02", ""),
                Arguments.of("UTCID03", "   \n  \n"),
                // Chỉ có khối sdks: hai khoá dart/flutter thụt 2 dấu cách y hệt tên package.
                Arguments.of("UTCID05", "sdks:\n  dart: \">=3.0.0\"\n"),
                Arguments.of("UTCID07", "packages:\nsdks:\n  dart: \">=3.0.0\"\n")
        );
    }

    @ParameterizedTest(name = "UT26 {0}: không bóc được tên nào → tập rỗng")
    @MethodSource("ut26_khongBocDuoc")
    @DisplayName("UT26 — không đọc được thì phải là \"không biết\" (tập rỗng), không phải \"ảnh chỉ có flutter\"")
    void ut26_khongBocDuocTraTapRong(String utcid, String lock) {
        Set<String> ra = ExamService.goiTuLock(lock);

        assertTrue(ra.isEmpty(),
                utcid + ": tập rỗng mới là \"không biết\"; trả {flutter, flutter_test} sẽ bị hiểu"
                        + " là ảnh thiếu mọi package và chặn oan cả bộ đề. Đang trả: " + ra);
    }

    @Test
    @DisplayName("UT26 UTCID04 — bóc đúng tên package, không nuốt nhầm khoá của khối sdks")
    void ut26_utcid04_bocDungTenPackage() {
        Set<String> ra = ExamService.goiTuLock(LOCK_DAY_DU);

        assertEquals(Set.of("flutter", "flutter_test", "intl", "sqflite"), ra);
        assertFalse(ra.contains("dart"), "khoá trong khối sdks: thụt y hệt nhưng không phải package");
    }

    @Test
    @DisplayName("UT26 UTCID06 — một gói vẫn đủ ngưỡng (tổng 3 tên > 2)")
    void ut26_utcid06_motGoiVanDuNguong() {
        Set<String> ra = ExamService.goiTuLock("packages:\n  intl:\n    version: \"0.19.0\"\n");

        assertEquals(Set.of("flutter", "flutter_test", "intl"), ra);
    }

    @Test
    @DisplayName("UT26 UTCID08 — dòng comment và tab thay khoảng trắng không làm lệch kết quả")
    void ut26_utcid08_commentVaTab() {
        String lock = "# Generated by pub\npackages:\n\tintl:\n\t\tversion: \"0.19.0\"\n"
                + "  sqflite:\n    version: \"2.3.0\"\n";

        assertEquals(Set.of("flutter", "flutter_test", "intl", "sqflite"), ExamService.goiTuLock(lock));
    }

    @Test
    @DisplayName("UT26 UTCID09 — thuộc tính của gói (thụt 4 dấu cách) không bị nhận nhầm là tên gói")
    void ut26_utcid09_thuocTinhKhongPhaiTenGoi() {
        String lock = """
                packages:
                  intl:
                    dependency: "direct main"
                    description:
                      name: intl
                      url: "https://pub.dev"
                    source: hosted
                  sqflite:
                    source: hosted
                """;

        Set<String> ra = ExamService.goiTuLock(lock);

        assertEquals(Set.of("flutter", "flutter_test", "intl", "sqflite"), ra);
        assertFalse(ra.contains("description"), "description: là thuộc tính, không phải tên gói");
        assertFalse(ra.contains("source"), "source: là thuộc tính, không phải tên gói");
    }

    // ══════════════════ UT27 — ExamService.listManagedPackages ══════════════════

    /** Dựng thư mục grader-base giả. locateTemplateDir nhận ra nó nhờ Dockerfile.base. */
    private ExamService examVoiPubspec(String ten, String pubspec) throws Exception {
        Path base = Files.createDirectories(thuMuc.resolve(ten));
        Files.writeString(base.resolve("Dockerfile.base"), "FROM scratch\n", StandardCharsets.UTF_8);
        if (pubspec != null) {
            Files.writeString(base.resolve("pubspec.base.yaml"), pubspec, StandardCharsets.UTF_8);
        }
        ExamService svc = new ExamService();
        datField(svc, "templateDir", base.toAbsolutePath().toString());
        return svc;
    }

    private static final String PUBSPEC_DU = """
            name: exam_project
            environment:
              sdk: ">=3.0.0 <4.0.0"
            dependencies:
              flutter:
                sdk: flutter
              intl: ^0.19.0
              sqflite: ^2.3.0
            dev_dependencies:
              flutter_test:
                sdk: flutter
              flutter_lints: ^4.0.0
            """;

    private static Map<String, Map<String, Object>> theoTen(List<Map<String, Object>> rows) {
        Map<String, Map<String, Object>> ra = new LinkedHashMap<>();
        rows.forEach(r -> ra.put(String.valueOf(r.get("name")), r));
        return ra;
    }

    @Test
    @DisplayName("UT27 UTCID01 — đọc cả dev_dependencies và khoá đúng các gói lõi")
    void ut27_utcid01_docCaDevDependencies() throws Exception {
        ExamService svc = examVoiPubspec("base1", PUBSPEC_DU);

        Map<String, Map<String, Object>> rows = theoTen(svc.listManagedPackages());

        assertEquals(Set.of("flutter", "intl", "sqflite", "flutter_test", "flutter_lints"), rows.keySet(),
                "flutter_test nằm ở dev_dependencies — bỏ khối đó là bảng tick thiếu đúng gói mọi bài đều cần");
        assertEquals("(flutter sdk)", rows.get("flutter").get("version"));
        assertEquals("^0.19.0", rows.get("intl").get("version"));
        assertEquals(true, rows.get("flutter").get("protected"));
        assertEquals(true, rows.get("flutter_test").get("protected"));
        assertEquals(true, rows.get("flutter_lints").get("protected"),
                "flutter_lints chỉ để phân tích mã, khoá lại để không ai xoá rồi tưởng đã cấm được gì");
        assertEquals(false, rows.get("intl").get("protected"));
        assertEquals(false, rows.get("sqflite").get("protected"));
    }

    @Test
    @DisplayName("UT27 UTCID02 — không có pubspec.base.yaml thì trả danh sách rỗng, không ném")
    void ut27_utcid02_khongCoPubspec() throws Exception {
        ExamService svc = examVoiPubspec("base2", null);

        assertTrue(svc.listManagedPackages().isEmpty());
    }

    @Test
    @DisplayName("UT27 UTCID03 — chỉ có dependencies thì không có dòng nào của dev_dependencies")
    void ut27_utcid03_chiCoDependencies() throws Exception {
        ExamService svc = examVoiPubspec("base3", """
                name: exam_project
                dependencies:
                  flutter:
                    sdk: flutter
                  intl: ^0.19.0
                  sqflite: ^2.3.0
                """);

        assertEquals(Set.of("flutter", "intl", "sqflite"), theoTen(svc.listManagedPackages()).keySet());
    }

    @Test
    @DisplayName("UT27 UTCID04 — dòng comment và dòng trống bị bỏ qua, kết quả không đổi")
    void ut27_utcid04_commentVaDongTrong() throws Exception {
        ExamService svc = examVoiPubspec("base4", """
                name: exam_project

                # Thu vien dung chung cho moi de
                dependencies:

                  flutter:
                    sdk: flutter
                  # intl de format tien te
                  intl: ^0.19.0
                """);

        assertEquals(Set.of("flutter", "intl"), theoTen(svc.listManagedPackages()).keySet());
    }

    @Test
    @DisplayName("UT27 UTCID05 — nội dung hỏng vẫn không ném, chỉ trả phần đọc được")
    void ut27_utcid05_noiDungHong() throws Exception {
        ExamService svc = examVoiPubspec("base5", "khong phai yaml :::: [[[\n\t\t\n");

        assertTrue(svc.listManagedPackages().isEmpty());
    }

    // ══════════════════ UT29 — ExamService.applyPackages ══════════════════

    @Test
    @DisplayName("UT29 UTCID03 — đang build dở thì từ chối lượt build thứ hai")
    void ut29_utcid03_dangBuildThiTuChoi() throws Exception {
        ExamService svc = examVoiPubspec("base-apply", PUBSPEC_DU);
        datField(svc, "envBuilding", true);

        // Phải khai version: từ 19/9 applyPackages kiểm version cho TỪNG gói TRƯỚC khi chạm
        // tới cờ envBuilding, nên gói thiếu version sẽ trượt ở cổng khác và ca này đo nhầm chỗ.
        IllegalStateException loi = assertThrows(IllegalStateException.class,
                () -> svc.applyPackages(List.of(Map.of("name", "intl", "version", "^0.19.0"))));

        assertEquals("Đang build môi trường, vui lòng đợi build xong.", loi.getMessage());
    }

    @Test
    @DisplayName("UT29 UTCID01 — trả về NGAY với trạng thái RESOLVING, không đợi luồng nền")
    void ut29_utcid01_traVeNgayKhongDoiLuongNen() throws Exception {
        ExamService svc = examVoiPubspec("base-apply2", PUBSPEC_DU);

        long truoc = System.currentTimeMillis();
        Map<String, Object> ra = svc.applyPackages(List.of(Map.of("name", "intl", "version", "^0.19.0")));
        long ton = System.currentTimeMillis() - truoc;

        assertEquals("RESOLVING", ra.get("status"),
                "phải báo đang xử lý ngay, vì phần nặng chạy ở luồng nền");
        assertTrue(ra.containsKey("building") && ra.containsKey("message") && ra.containsKey("log"),
                "buildStatus phải đủ khoá cho frontend poll");
        assertTrue(ton < 3000, "applyPackages không được chặn luồng gọi, đang tốn " + ton + "ms");
    }

    // ══════════════════ UT30 / UT31 — GradingRuntimeSettingsService ══════════════════

    private GradingRuntimeSettingRepository repo;
    private GradingRuntimeSettingsService cauHinh;
    private final AtomicInteger soWorkerDaDoi = new AtomicInteger(-1);

    @BeforeEach
    void dungCauHinhGia() throws Exception {
        repo = mock(GradingRuntimeSettingRepository.class);
        when(repo.findById(any())).thenReturn(Optional.empty());
        when(repo.save(any())).thenAnswer(inv -> inv.getArgument(0));

        cauHinh = new GradingRuntimeSettingsService();
        datField(cauHinh, "repo", repo);
        datField(cauHinh, "defaultCpusRaw", "2.0");
        datField(cauHinh, "defaultMemoryRaw", "2048m");
        datField(cauHinh, "defaultMaxConcurrent", 3);
        datField(cauHinh, "defaultTimeoutSeconds", 240);
        datField(cauHinh, "maxConcurrentLimit", 16);
        cauHinh.bindConcurrencyApplier(soWorkerDaDoi::set);
        cauHinh.resetToDefaults("dung-ban-dau");            // đưa về trạng thái biết trước
    }

    @SuppressWarnings("unchecked")
    private Map<String, Object> khoa(String ten) {
        return (Map<String, Object>) cauHinh.describe().get(ten);
    }

    private double so(String nhom, String khoa) {
        return ((Number) khoa(nhom).get(khoa)).doubleValue();
    }

    /** Bộ giá trị hợp lệ suy từ chính giới hạn của máy đang chạy test. */
    private Map<String, Object> than(double cpus, int mem, int con, int timeout) {
        Map<String, Object> b = new LinkedHashMap<>();
        b.put("cpus", cpus);
        b.put("memoryMb", mem);
        b.put("maxConcurrent", con);
        b.put("timeoutSeconds", timeout);
        return b;
    }

    @Test
    @DisplayName("UT30 UTCID01 — giá trị hợp lệ được lưu và áp ngay số worker")
    void ut30_utcid01_giaTriHopLe() {
        // Kẹp vào khoảng của máy đang chạy: giới hạn CPU/RAM phụ thuộc docker info.
        double cpus = Math.min(Math.max(2.0, so("limits", "cpusMin")), so("limits", "cpusMax"));
        int mem = (int) Math.min(Math.max(2048, so("limits", "memoryMbMin")), so("limits", "memoryMbMax"));
        int con = (int) Math.min(Math.max(3, so("limits", "maxConcurrentMin")), so("limits", "maxConcurrentMax"));

        Map<String, Object> ra = cauHinh.update(than(cpus, mem, con, 240), "nguoi-cham");

        @SuppressWarnings("unchecked")
        Map<String, Object> settings = (Map<String, Object>) ra.get("settings");
        assertEquals(cpus, ((Number) settings.get("cpus")).doubleValue());
        assertEquals(mem, ((Number) settings.get("memoryMb")).intValue());
        assertEquals(con, ((Number) settings.get("maxConcurrent")).intValue());
        assertEquals(240, ((Number) settings.get("timeoutSeconds")).intValue());
        assertEquals("nguoi-cham", ra.get("updatedBy"));
        assertEquals(con, soWorkerDaDoi.get(), "số bài song song phải có hiệu lực NGAY");
    }

    @Test
    @DisplayName("UT30 UTCID02/03 — đúng hai biên đều được nhận")
    void ut30_utcid02_03_haiBien() {
        assertEquals((int) so("limits", "timeoutSecondsMin"),
                ((Number) ((Map<?, ?>) cauHinh.update(than(so("limits", "cpusMin"),
                        (int) so("limits", "memoryMbMin"), (int) so("limits", "maxConcurrentMin"),
                        (int) so("limits", "timeoutSecondsMin")), "bien-duoi").get("settings"))
                        .get("timeoutSeconds")).intValue(), "UTCID02: biên dưới");

        assertEquals((int) so("limits", "timeoutSecondsMax"),
                ((Number) ((Map<?, ?>) cauHinh.update(than(so("limits", "cpusMax"),
                        (int) so("limits", "memoryMbMax"), (int) so("limits", "maxConcurrentMax"),
                        (int) so("limits", "timeoutSecondsMax")), "bien-tren").get("settings"))
                        .get("timeoutSeconds")).intValue(), "UTCID03: biên trên");
    }

    static Stream<Arguments> ut30_ngoaiKhoang() {
        return Stream.of(
                Arguments.of("UTCID04", "cpus", -1, "Số CPU mỗi bài phải trong khoảng"),
                Arguments.of("UTCID05", "cpus", +1, "Số CPU mỗi bài phải trong khoảng"),
                Arguments.of("UTCID07", "memoryMb", -1, "RAM mỗi bài phải trong khoảng"),
                Arguments.of("UTCID08", "memoryMb", +1, "RAM mỗi bài phải trong khoảng"),
                Arguments.of("UTCID09", "maxConcurrent", -1, "Số bài chấm song song phải trong khoảng"),
                Arguments.of("UTCID10", "maxConcurrent", +1, "Số bài chấm song song phải trong khoảng"),
                Arguments.of("UTCID11", "timeoutSeconds", -1, "Thời gian tối đa mỗi bài phải trong khoảng"),
                Arguments.of("UTCID12", "timeoutSeconds", +1, "Thời gian tối đa mỗi bài phải trong khoảng")
        );
    }

    @ParameterizedTest(name = "UT30 {0}: {1} lệch biên {2}")
    @MethodSource("ut30_ngoaiKhoang")
    @DisplayName("UT30 — ra ngoài khoảng là NÉM, tuyệt đối không tự cắt gọt cho vừa")
    void ut30_ngoaiKhoangThiNem(String utcid, String truong, int huong, String moDau) {
        Map<String, Object> than = than(so("limits", "cpusMin"), (int) so("limits", "memoryMbMin"),
                (int) so("limits", "maxConcurrentMin"), (int) so("limits", "timeoutSecondsMin"));
        String bien = truong + (huong < 0 ? "Min" : "Max");
        double lech = "cpus".equals(truong) ? 0.5 : 1;
        than.put(truong, so("limits", bien) + huong * lech);

        IllegalArgumentException loi = assertThrows(IllegalArgumentException.class,
                () -> cauHinh.update(than, "nguoi-cham"));

        assertTrue(loi.getMessage().startsWith(moDau),
                utcid + ": lời báo phải nói rõ ô nào sai, đang là: " + loi.getMessage());
    }

    @Test
    @DisplayName("UT30 UTCID06 — CPU được làm tròn 1 chữ số trước khi kiểm khoảng")
    void ut30_utcid06_lamTronCpu() {
        double hopLe = Math.min(Math.max(2.0, so("limits", "cpusMin")), so("limits", "cpusMax"));
        Map<String, Object> than = than(hopLe + 0.04, (int) so("limits", "memoryMbMin"),
                (int) so("limits", "maxConcurrentMin"), 240);

        Map<?, ?> settings = (Map<?, ?>) cauHinh.update(than, "nguoi-cham").get("settings");

        assertEquals(hopLe, ((Number) settings.get("cpus")).doubleValue(), 1e-9);
    }

    @Test
    @DisplayName("UT30 UTCID13 — thân rỗng thì giữ nguyên giá trị đang có, không hạ về 0")
    void ut30_utcid13_thanRongGiuGiaTriCu() {
        Map<?, ?> truoc = (Map<?, ?>) cauHinh.describe().get("settings");

        Map<?, ?> sau = (Map<?, ?>) cauHinh.update(new LinkedHashMap<>(), "nguoi-cham").get("settings");

        assertEquals(truoc.get("cpus"), sau.get("cpus"));
        assertEquals(truoc.get("memoryMb"), sau.get("memoryMb"));
        assertEquals(truoc.get("maxConcurrent"), sau.get("maxConcurrent"));
        assertEquals(truoc.get("timeoutSeconds"), sau.get("timeoutSeconds"));
    }

    @Test
    @DisplayName("UT30 UTCID14 — ghi DB hỏng phải báo rõ là CHƯA LƯU ĐƯỢC")
    void ut30_utcid14_ghiDbHong() {
        when(repo.save(any())).thenThrow(new RuntimeException("mat ket noi"));
        Map<String, Object> than = than(so("limits", "cpusMin"), (int) so("limits", "memoryMbMin"),
                (int) so("limits", "maxConcurrentMin"), 240);

        IllegalStateException loi = assertThrows(IllegalStateException.class,
                () -> cauHinh.update(than, "nguoi-cham"));

        assertTrue(loi.getMessage().startsWith("Không lưu được cấu hình vào cơ sở dữ liệu"),
                "người dùng phải biết là chưa lưu được, không được im lặng: " + loi.getMessage());
    }

    @Test
    @DisplayName("UT30 UTCID15 — actor null vẫn lưu được")
    void ut30_utcid15_actorNull() {
        Map<String, Object> than = than(so("limits", "cpusMin"), (int) so("limits", "memoryMbMin"),
                (int) so("limits", "maxConcurrentMin"), 240);

        Map<String, Object> ra = cauHinh.update(than, null);

        assertEquals(null, ra.get("updatedBy"));
    }

    @Test
    @DisplayName("UT31 UTCID01 — reset trả đúng giá trị trong application.yml")
    void ut31_utcid01_traDungMacDinh() {
        cauHinh.update(than(so("limits", "cpusMin"), (int) so("limits", "memoryMbMin"),
                (int) so("limits", "maxConcurrentMin"), 900), "truoc-khi-reset");

        Map<String, Object> ra = cauHinh.resetToDefaults("nguoi-cham");

        @SuppressWarnings("unchecked")
        Map<String, Object> settings = (Map<String, Object>) ra.get("settings");
        assertEquals(2.0, ((Number) settings.get("cpus")).doubleValue());
        assertEquals(2048, ((Number) settings.get("memoryMb")).intValue());
        assertEquals(3, ((Number) settings.get("maxConcurrent")).intValue());
        assertEquals(240, ((Number) settings.get("timeoutSeconds")).intValue());
        assertEquals("nguoi-cham", ra.get("updatedBy"));
        assertEquals(3, soWorkerDaDoi.get());
    }

    @Test
    @DisplayName("UT31 UTCID02/03 — RAM khai kiểu docker (\"2g\") quy về MB; khai hỏng rơi về 2048")
    void ut31_utcid02_03_quyDoiRam() throws Exception {
        datField(cauHinh, "defaultMemoryRaw", "2g");
        assertEquals(2048, ((Number) ((Map<?, ?>) cauHinh.resetToDefaults("a").get("settings"))
                .get("memoryMb")).intValue(), "UTCID02");

        datField(cauHinh, "defaultMemoryRaw", "khong-phai-so");
        assertEquals(2048, ((Number) ((Map<?, ?>) cauHinh.resetToDefaults("a").get("settings"))
                .get("memoryMb")).intValue(), "UTCID03: khai hỏng thì rơi về mặc định an toàn");
    }

    @Test
    @DisplayName("UT31 UTCID04 — ghi DB hỏng thì reset cũng phải báo lỗi rõ")
    void ut31_utcid04_ghiDbHong() {
        when(repo.save(any())).thenThrow(new RuntimeException("mat ket noi"));

        assertTrue(assertThrows(IllegalStateException.class, () -> cauHinh.resetToDefaults("nguoi-cham"))
                .getMessage().startsWith("Không lưu được cấu hình vào cơ sở dữ liệu"));
    }

    static Stream<Arguments> ut31_actor() {
        return Stream.of(
                Arguments.of("UTCID05", (String) null),
                Arguments.of("UTCID06", "")
        );
    }

    @ParameterizedTest(name = "UT31 {0}: actor = [{1}]")
    @MethodSource("ut31_actor")
    @DisplayName("UT31 — actor rỗng hay null đều không chặn được lần reset")
    void ut31_actorRong(String utcid, String actor) {
        Map<String, Object> ra = cauHinh.resetToDefaults(actor);

        assertEquals(actor, ra.get("updatedBy"), utcid);
        assertEquals(2.0, ((Number) ((Map<?, ?>) ra.get("settings")).get("cpus")).doubleValue(), utcid);
    }

    @Test
    @DisplayName("UT31 UTCID07/08 — applier chưa bind, hoặc bind mà ném, đều không làm hỏng lần reset")
    void ut31_utcid07_08_applierHong() throws Exception {
        GradingRuntimeSettingsService rieng = new GradingRuntimeSettingsService();
        datField(rieng, "repo", repo);
        datField(rieng, "defaultCpusRaw", "2.0");
        datField(rieng, "defaultMemoryRaw", "2048m");
        datField(rieng, "defaultMaxConcurrent", 3);
        datField(rieng, "defaultTimeoutSeconds", 240);
        datField(rieng, "maxConcurrentLimit", 16);

        // UTCID07: chưa bind applier.
        assertEquals(2.0, ((Number) ((Map<?, ?>) rieng.resetToDefaults("a").get("settings"))
                .get("cpus")).doubleValue(), "UTCID07");

        // UTCID08: applier ném — cấu hình vẫn phải lưu xong, chỉ ghi warn.
        rieng.bindConcurrencyApplier(n -> { throw new IllegalStateException("worker chet"); });
        assertEquals(3, ((Number) ((Map<?, ?>) rieng.resetToDefaults("a").get("settings"))
                .get("maxConcurrent")).intValue(), "UTCID08");
    }

    /** Bản ghi cấu hình là singleton — mọi lần lưu phải ghi vào cùng một dòng. */
    @Test
    @DisplayName("UT30/UT31 — cấu hình luôn ghi vào đúng một dòng singleton")
    void luonGhiVaoDongSingleton() {
        org.mockito.ArgumentCaptor<GradingRuntimeSetting> bat =
                org.mockito.ArgumentCaptor.forClass(GradingRuntimeSetting.class);

        cauHinh.resetToDefaults("nguoi-cham");

        org.mockito.Mockito.verify(repo, org.mockito.Mockito.atLeastOnce()).save(bat.capture());
        bat.getAllValues().forEach(row ->
                assertEquals(GradingRuntimeSetting.SINGLETON_ID, row.getId()));
    }
}
